# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message_chassisconfig.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='message_chassisconfig.proto',
  package='rbk.protocol',
  syntax='proto3',
  serialized_pb=_b('\n\x1bmessage_chassisconfig.proto\x12\x0crbk.protocol\"u\n\x15Message_ChassisConfig\x12\t\n\x01\x45\x18\x01 \x01(\x02\x12\t\n\x01R\x18\x02 \x03(\x02\x12\x14\n\x0c\x65ncoderLines\x18\x03 \x01(\x05\x12\x16\n\x0ereductionRatio\x18\x04 \x01(\x02\x12\x18\n\x10motorMaxSpeedRpm\x18\x05 \x01(\x05\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_MESSAGE_CHASSISCONFIG = _descriptor.Descriptor(
  name='Message_ChassisConfig',
  full_name='rbk.protocol.Message_ChassisConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='E', full_name='rbk.protocol.Message_ChassisConfig.E', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='R', full_name='rbk.protocol.Message_ChassisConfig.R', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='encoderLines', full_name='rbk.protocol.Message_ChassisConfig.encoderLines', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='reductionRatio', full_name='rbk.protocol.Message_ChassisConfig.reductionRatio', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='motorMaxSpeedRpm', full_name='rbk.protocol.Message_ChassisConfig.motorMaxSpeedRpm', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=162,
)

DESCRIPTOR.message_types_by_name['Message_ChassisConfig'] = _MESSAGE_CHASSISCONFIG

Message_ChassisConfig = _reflection.GeneratedProtocolMessageType('Message_ChassisConfig', (_message.Message,), dict(
  DESCRIPTOR = _MESSAGE_CHASSISCONFIG,
  __module__ = 'message_chassisconfig_pb2'
  # @@protoc_insertion_point(class_scope:rbk.protocol.Message_ChassisConfig)
  ))
_sym_db.RegisterMessage(Message_ChassisConfig)


# @@protoc_insertion_point(module_scope)
