import rsa
(pubk, prik) = rsa.newkeys(512)
print(prik)
f = open('privkey.pem', 'wb')
f.write(prik._save_pkcs1_pem())
f.close()

f = open('pubkey.pem', 'wb')
f.write(pubk._save_pkcs1_pem())
f.close()

f = open('rsa_priv.txt', 'w')
f.write('N = ')
f.write(hex(prik.n).upper()[2:])
f.write('\nE = ')
f.write(hex(prik.e).upper()[2:])
f.write('\nD = ')
f.write(hex(prik.d).upper()[2:])
f.write('\nP = ')
f.write(hex(prik.p).upper()[2:])
f.write('\nQ = ')
f.write(hex(prik.q).upper()[2:])
f.write('\nDP = ')
f.write(hex(prik.exp1).upper()[2:])
f.write('\nDQ = ')
f.write(hex(prik.exp2).upper()[2:])
f.write('\nQP = ')
f.write(hex(prik.coef).upper()[2:])
f.close()

f = open('rsa_pub.txt', 'w')
f.write('N = ')
f.write(hex(prik.n).upper()[2:])
f.write('\nE = ')
f.write(hex(prik.e).upper()[2:])
f.close()
